##
## @author omargo33@hotmail.com
## @since 2023-08-13

##
## Servicio de placas con docker
version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - placas-network


networks:
  placas-network:
    driver: bridge

